#!/bin/sh

docker/api/prepare.sh

docker/app/prepare.sh

# must follow app build (i.e. after that node static files have been generated)
docker/web/prepare.sh

# After prepare run image building, replace the TAG's value `r2` with your current release number
# TAG=r2 docker-compose build
