export var SET_BIRTHDAY_PERIOD = 'SET_BIRTHDAY_PERIOD';
export var SET_BIRTHDAY_PERIOD_BY_DATE = 'SET_BIRTHDAY_PERIOD_BY_DATE';
export var EXTEND_BIRTHDAY_PERIOD_LEFT = 'EXTEND_BIRTHDAY_PERIOD_LEFT';
export var EXTEND_BIRTHDAY_PERIOD_RIGHT = 'EXTEND_BIRTHDAY_PERIOD_RIGHT';
export var SCROLLED_TO_DATE = 'SCROLLED_TO_DATE';
