export const SET_BIRTHDAY_PERIOD = 'SET_BIRTHDAY_PERIOD';
export const SET_BIRTHDAY_PERIOD_BY_DATE = 'SET_BIRTHDAY_PERIOD_BY_DATE';
export const EXTEND_BIRTHDAY_PERIOD_LEFT = 'EXTEND_BIRTHDAY_PERIOD_LEFT';
export const EXTEND_BIRTHDAY_PERIOD_RIGHT = 'EXTEND_BIRTHDAY_PERIOD_RIGHT';
export const SCROLLED_TO_DATE = 'SCROLLED_TO_DATE';
