export const SET_CURRENT_UNIT_ID = 'SET_CURRENT_UNIT_ID';
export const SET_HIGHLIGHTED_UNIT_ID = 'SET_HIGHLIGHTED_UNIT_ID';
export const SET_CURRENT_EMPLOYMENT_ID = 'SET_CURRENT_EMPLOYMENT_ID';
export const SET_CURRENT_CONTACT_ID = 'SET_CURRENT_CONTACT_ID';
export const SCROLL_TO_UNIT = 'SCROLL_TO_UNIT';
export const SCROLLED_TO_UNIT = 'SCROLLED_TO_UNIT';
