export var SET_CURRENT_UNIT_ID = 'SET_CURRENT_UNIT_ID';
export var SET_HIGHLIGHTED_UNIT_ID = 'SET_HIGHLIGHTED_UNIT_ID';
export var SET_CURRENT_EMPLOYMENT_ID = 'SET_CURRENT_EMPLOYMENT_ID';
export var SET_CURRENT_CONTACT_ID = 'SET_CURRENT_CONTACT_ID';
export var SCROLL_TO_UNIT = 'SCROLL_TO_UNIT';
export var SCROLLED_TO_UNIT = 'SCROLLED_TO_UNIT';
