export FETCH_INITIAL_STATE_REQUEST = 'FETCH_INITIAL_STATE_REQUEST'
export FETCH_INITIAL_STATE_SUCCESS = 'FETCH_INITIAL_STATE_SUCCESS'
export FETCH_INITIAL_STATE_FAILURE = 'FETCH_INITIAL_STATE_FAILURE'
