export POP_LAYOUT_BLOCK = 'POP_LAYOUT_BLOCK'
export SINK_LAYOUT_BLOCK = 'SINK_LAYOUT_BLOCK'

export LAYOUT_BLOCK_STRUCTURE = 'structure'
export LAYOUT_BLOCK_UNIT_INFO = 'unit-info'
export LAYOUT_BLOCK_EMPLOYEE_INFO = 'employee-info'
export LAYOUT_BLOCK_SEARCH_RESULTS = 'search-results'
export LAYOUT_BLOCK_FAVORITES = 'favorites'
export LAYOUT_BLOCK_RECENT = 'recent'

export DEFAULT_LAYOUT = [
  LAYOUT_BLOCK_RECENT
  LAYOUT_BLOCK_FAVORITES
  LAYOUT_BLOCK_EMPLOYEE_INFO
  LAYOUT_BLOCK_UNIT_INFO
  LAYOUT_BLOCK_STRUCTURE
  LAYOUT_BLOCK_SEARCH_RESULTS
]

# stay synced with  common/css/resources/_layouts.sass
export ONE_COLUMN_MAX = 959
export TWO_COLUMN_MIN = 960
export TWO_COLUMN_MAX = 1599
export THREE_COLUMN_MIN = 1600
export THREE_COLUMN_MAX = 1999
export FOUR_COLUMN_MIN = 2000
