export SET_HUMAN_QUERY = 'SET_HUMAN_QUERY'
export SET_MACHINE_QUERY = 'SET_MACHINE_QUERY'
export SEND_QUERY = 'SEND_QUERY'
export SET_CURRENT_RESULTS = 'SET_CURRENT_RESULTS'
export SET_RESULTS_TYPE = 'SET_RESULTS_TYPE'
export SET_RESULTS_SOURCE = 'SET_RESULTS_SOURCE'

export RESULTS_SOURCE_BIRTHDAY = 'birthday'
export RESULTS_SOURCE_QUERY = 'query'
export DEFAULT_RESULTS_SOURCE = RESULTS_SOURCE_QUERY
