export const SET_HUMAN_QUERY = 'SET_HUMAN_QUERY';
export const SET_MACHINE_QUERY = 'SET_MACHINE_QUERY';
export const SEND_QUERY = 'SEND_QUERY';
export const SET_CURRENT_RESULTS = 'SET_CURRENT_RESULTS';
export const SET_RESULTS_TYPE = 'SET_RESULTS_TYPE';
export const SET_RESULTS_SOURCE = 'SET_RESULTS_SOURCE';

export const RESULTS_SOURCE_BIRTHDAY = 'birthday';
export const RESULTS_SOURCE_QUERY = 'query';
export const DEFAULT_RESULTS_SOURCE = RESULTS_SOURCE_QUERY;
