export URL_PARAM_UNIT = 'unit'
export URL_PARAM_EMPLOYMENT = 'employee'
export URL_PARAM_CONTACT = 'contact'
export URL_PARAM_LAYOUT = 'l'
export URL_PARAM_RESULTS_SOURCE = 's'
export URL_PARAM_BIRTHDAY_PERIOD = 'birthday'
export URL_PARAM_QUERY = 'q'
